### ISSUE TITLE
Add file relative to current open file

### ISSUE THREAD

**Issue by okian** [bgse/vsc-addfileextension#11]
That would be great if we could add  file relative to current open file when some was open for example
 if I'm editing `src/db/models/car.ts` and adding `people.ts` created in  `src/db/models/people.ts` 
 if I'm editing `src/db/models/car.ts` and adding `../config.ts` created in  `src/db/config.ts`
 if I'm editing `src/db/models/car.ts` and adding `foo/bar.ts` created in  `src/db/models/foo/bar.ts`
and in case It's needed to make a file relative to the project folder just start path with `/` like `/tsconfig.json`

**Comment by bgse** [comment]
Good suggestion, I'll add this in the next update.

**Comment by stkb** [comment]
Would also very much like it to work this way :)

I can also have a go myself if you don't have time

**Comment by bgse** [comment]
@stkb Sure, PRs are always welcome :)

I'll probably not have the time to look at it before late next week.
