### ISSUE TITLE
Windows: editor not coming up when adding file

### ISSUE THREAD

**Issue by bgse** [bgse/vsc-addfileextension#4]
from console:

cannot open untitled:e%3A%5Cworkshop-node-electron-app/tst/myfile.js. Detail: expected URI untitled:e%3A%5Cworkshop-node-electron-app/tst/myfile.js BUT GOT untitled:e%3A%5Cworkshop-node-electron-app%5Ctst%5Cmyfile.js

**Comment by Xiot** [comment]
In windows the path seperator is \
Should probably use the import 'path' to do path manipulations. It has a pathSeperator on it to get the correct one for the OS

**Comment by bgse** [comment]
@Xiot Indeed, should have known better. I shall now watch 10 months worth of windows updates as a punishment :)
